version: '3.9'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - frontend
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
  frontend:
    container_name: frontend
    build: .
    ports:
      - "3000:3000"